<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Kelsey Carlston">
<meta name="dcterms.date" content="2023-11-17">

<title>ECON 355 - Regression - Regression Workbook</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../styles.css">
<link rel="stylesheet" href="webex.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">ECON 355 - Regression</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html">
 <span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-r-walkthroughs" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">R Walkthroughs</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-r-walkthroughs">    
        <li>
    <a class="dropdown-item" href="../03_r_lectures/lecture_1_getting_started.html">
 <span class="dropdown-text">Lesson 1 - Getting Started</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../03_r_lectures/lecture_2_loading_data.html">
 <span class="dropdown-text">Lesson 2 - Loading Data</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-labs" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Labs</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-labs">    
        <li>
    <a class="dropdown-item" href="../02_assignments/lab-02.html">
 <span class="dropdown-text">Lab 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../02_assignments/lab-03.html">
 <span class="dropdown-text">Lab 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../02_assignments/lab-04.html">
 <span class="dropdown-text">Lab 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../02_assignments/lab-05.html">
 <span class="dropdown-text">Lab 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../02_assignments/lab-06.html">
 <span class="dropdown-text">Lab 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../02_assignments/lab-07.html">
 <span class="dropdown-text">Lab 7</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../02_assignments/lab-08.html">
 <span class="dropdown-text">Lab 8</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../02_assignments/lab-09.html">
 <span class="dropdown-text">Lab 9</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../02_assignments/lab-10.html">
 <span class="dropdown-text">Lab 10</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../02_assignments/mini_lab-ttests.html">
 <span class="dropdown-text">T Tests Mini Lab</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-resources" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Resources</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-resources">    
        <li>
    <a class="dropdown-item" href="../00_descriptive/descriptives.html">
 <span class="dropdown-text">Descriptive Statistics</span></a>
  </li>  
    </ul>
  </li>
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#regression-workbook" id="toc-regression-workbook" class="nav-link active" data-scroll-target="#regression-workbook">Regression Workbook</a>
  <ul class="collapse">
  <li><a href="#simple-linear-regression" id="toc-simple-linear-regression" class="nav-link" data-scroll-target="#simple-linear-regression">Simple Linear Regression</a>
  <ul class="collapse">
  <li><a href="#model-diagnostics" id="toc-model-diagnostics" class="nav-link" data-scroll-target="#model-diagnostics">Model Diagnostics</a></li>
  <li><a href="#extra-practice" id="toc-extra-practice" class="nav-link" data-scroll-target="#extra-practice">Extra Practice</a></li>
  </ul></li>
  <li><a href="#multiple-linear-regression" id="toc-multiple-linear-regression" class="nav-link" data-scroll-target="#multiple-linear-regression">Multiple Linear Regression</a>
  <ul class="collapse">
  <li><a href="#college-and-beyond-example" id="toc-college-and-beyond-example" class="nav-link" data-scroll-target="#college-and-beyond-example">College and Beyond Example</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Regression Workbook</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Kelsey Carlston </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 17, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="regression-workbook" class="level1">
<h1>Regression Workbook</h1>
<p>The goal of this workbook is to give you lots of hands-on practice with the regression topics we learned in class without adding extra assignments.</p>
<section id="simple-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="simple-linear-regression">Simple Linear Regression</h2>
<p><strong>Simple linear regression</strong> is a regression between one <span class="math inline">\(x\)</span> variable and one <span class="math inline">\(y\)</span> variable. It takes the form: <span class="math display">\[\hat{y_i}=\beta_0 + \beta_1*x_i\]</span> The formula to calculate <span class="math inline">\(\beta_1\)</span> is: <span class="math display">\[\beta_1 = \dfrac{cov(x,y)}{var(x)}=\dfrac{\sum_{i=1}^n(x_i-\bar{x})(y_i-\bar{y})}{\sum_{i=1}^n(x_i-\bar{x})^2}\]</span> The formula to calculate <span class="math inline">\(\beta_0\)</span> is: <span class="math display">\[\beta_0 = \bar{y}-\beta_1*\bar{x}\]</span></p>
<p>For our first example, we will be using the <code>cars</code> data set, which measures the speed in mph and stopping distance in feet for 50 observations of cars. We will create a simple regression to predict stopping distance using speed. Using the data in the table, calculate <span class="math inline">\(\beta_1\)</span>, <span class="math inline">\(\beta_0\)</span>, and the expected stopping distance if a car is going 7.15 mph.</p>
<table class="table">
<caption>Descriptive Statistics for Cars Data</caption>
<tbody>
<tr class="odd">
<td>Average Speed</td>
<td>15.4</td>
</tr>
<tr class="even">
<td>Average Stopping Distance</td>
<td>43.0</td>
</tr>
<tr class="odd">
<td>Covariance of Speed and Stopping Distance</td>
<td>109.9</td>
</tr>
<tr class="even">
<td>Variance of Speed</td>
<td>28.0</td>
</tr>
<tr class="odd">
<td>Variance of Stopping Distance</td>
<td>664.1</td>
</tr>
</tbody>
</table>
What is the value of <span class="math inline">\(\beta_1\)</span>?
<div id="radio_BOHBFOKLIG" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_BOHBFOKLIG" value=""> <span>0.17</span></label><label><input type="radio" autocomplete="off" name="radio_BOHBFOKLIG" value=""> <span>23.7</span></label><label><input type="radio" autocomplete="off" name="radio_BOHBFOKLIG" value="answer"> <span>3.93</span></label>
</div>
What is the value of <span class="math inline">\(\beta_0\)</span>?
<div id="radio_QNAKFXDNQP" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_QNAKFXDNQP" value=""> <span>27.6</span></label><label><input type="radio" autocomplete="off" name="radio_QNAKFXDNQP" value="answer"> <span>-17.5</span></label><label><input type="radio" autocomplete="off" name="radio_QNAKFXDNQP" value=""> <span>-153.6</span></label>
</div>
What is the expected stopping distance if speed is 7.15?
<div id="radio_CWUNJAPSIN" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_CWUNJAPSIN" value=""> <span>5.1</span></label><label><input type="radio" autocomplete="off" name="radio_CWUNJAPSIN" value=""> <span>25.3</span></label><label><input type="radio" autocomplete="off" name="radio_CWUNJAPSIN" value="answer"> <span>10.4</span></label>
</div>
<p>Regressions hardly ever perfectly accurately predict the outcome. The difference between the predicted/fitted value and the actual value is called the <strong>error</strong> or <strong>residual</strong>. The formula is: <span class="math inline">\(\varepsilon_i = y_i-\hat{y_i}\)</span>.</p>
What is the error for a car going 7.15mph that stops in 15.1 feet?
<div id="radio_VOYFZOCKDT" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_VOYFZOCKDT" value="answer"> <span>-4.7</span></label><label><input type="radio" autocomplete="off" name="radio_VOYFZOCKDT" value=""> <span>10.2</span></label><label><input type="radio" autocomplete="off" name="radio_VOYFZOCKDT" value=""> <span>7.9</span></label>
</div>
<section id="model-diagnostics" class="level3">
<h3 class="anchored" data-anchor-id="model-diagnostics">Model Diagnostics</h3>
<p>There are three primary things we use in a simple linear regression to see how good the model and its predictors are:</p>
<ul>
<li>The <span class="math inline">\(R^2\)</span> tells us <em>goodness of fit</em>, or how much predictive power the equation has.</li>
<li>The <span class="math inline">\(F\)</span> statistic can be used to test whether the model does significantly better than the mean, <span class="math inline">\(\bar{y}\)</span>, at predicting the value of <span class="math inline">\(y\)</span>.</li>
<li>The <span class="math inline">\(t\)</span> statistics and p-values associated with each coefficient tell us whether the <span class="math inline">\(x\)</span> values are significant predictors of <span class="math inline">\(y\)</span>. We can have a significant model even if some of the <span class="math inline">\(x\)</span> variables are not significant.</li>
</ul>
<section id="calculating-r2" class="level4">
<h4 class="anchored" data-anchor-id="calculating-r2">Calculating <span class="math inline">\(R^2\)</span></h4>
<p>To calculate the <span class="math inline">\(R^2\)</span>, we need to know the variation in <span class="math inline">\(y\)</span> that is predicted by the model. The Total Sum of Squares <span class="math inline">\((SST)\)</span> adds up all of the variation in y, the Regression Sum of Squares <span class="math inline">\((SSR)\)</span> adds up the variation explained by the model, and the Sum of Squared Errors <span class="math inline">\((SSE)\)</span> adds up all of the variation <strong>not</strong> explained by the model.</p>
<div class="cell" data-warnings="false" data-fig.asp="0.34">
<div class="cell-output-display">
<p><img src="regression_workbook_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid" style="width:100.0%"></p>
</div>
</div>
<p>Here are the formulas to calculate each of these:</p>
<p><span class="math display">\[
SST = \sum_{i=1}^n(y_i-\bar{y})^2 = SSE + SSR
\]</span></p>
<p><span class="math display">\[
SSE=\sum_{i=1}^n(y_i-\hat{y_i})^2
\]</span></p>
<p><span class="math display">\[
SSR=\sum_{i=1}^n(\hat{y_i}-\bar{y})^2
\]</span></p>
<p>The formula for <span class="math inline">\(R^2\)</span> is the total variation explained by the model divided by the total variation.</p>
<p><span class="math display">\[
R^2=\dfrac{SSR}{SST}=\dfrac{SST-SSE}{SST}
\]</span></p>
<p>The interpretation of the <span class="math inline">\(R^2\)</span> is: “<span class="math inline">\(R^2\)</span> % of the variation in <span class="math inline">\(y\)</span> can be explained by the model.”</p>
<p>The <span class="math inline">\(SSE\)</span> for the car model is 11,354, the <span class="math inline">\(SSR\)</span> is 21,185. Based on this, fill in the blank: “<input class="webex-solveme nospaces" size="4" data-answer="[&quot;60.3&quot;]"> percent of the variation in stopping distance can be explained by the speed of the car.”</p>
</section>
<section id="the-f-test" class="level4">
<h4 class="anchored" data-anchor-id="the-f-test">The F Test</h4>
<p>The point of calculating the <span class="math inline">\(F\)</span> statistic is to see if the model is statistically significantly better than just using the mean. The hypotheses are: <span class="math inline">\(H_0\)</span>: The model is NOT significantly better than using the mean, <span class="math inline">\(\bar{y}\)</span>, to predict <span class="math inline">\(y\)</span>. <span class="math inline">\(H_A\)</span>: The model IS better than using the mean to predict <span class="math inline">\(y\)</span>.</p>
<p>The <span class="math inline">\(F\)</span> stat is the ratio of the variation explained by the model to the variation not explained by the model. We need the Regression Mean Squares (<span class="math inline">\(MSR\)</span>) and the Mean Square Error (<span class="math inline">\(MSE\)</span>) to to calculate it. <span class="math display">\[
F = \dfrac{MSR}{MSE}=\dfrac{\dfrac{SSR}{DF_{SSR}}}{\dfrac{SSE}{DF_{SSE}}}
\]</span> where <span class="math inline">\(DF_{SSR} = k\)</span> and <span class="math inline">\(DF_{SSE} = n-k-1\)</span>, where <span class="math inline">\(k\)</span> is the number of coefficients or parameters and <span class="math inline">\(n\)</span> is the number of observations.</p>
<p>What is the <span class="math inline">\(F\)</span> statistic for the car regression?</p>
<p><input class="webex-solveme nospaces" size="4" data-answer="[&quot;89.6&quot;]"></p>
<p>Once we have the F-statistic, we can compare it to a known distribution to get a p-value. The p-value is the probability that we would see the values that we do if the model is NOT better than the mean at predicting <span class="math inline">\(y\)</span>. That means that the lower the p-value, the better our model is.</p>
<p>That value is statistically significant. What does a statistically significant F test generally mean about regression models?</p>
<div id="radio_RZCFJJNUZM" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_RZCFJJNUZM" value="answer"> <span>The model is significantly better than the null model.</span></label><label><input type="radio" autocomplete="off" name="radio_RZCFJJNUZM" value=""> <span>All of the variables in the model are statistically significant.</span></label><label><input type="radio" autocomplete="off" name="radio_RZCFJJNUZM" value=""> <span>The X variables are pratically important predictors of Y.</span></label>
</div>
</section>
<section id="t-tests-and-coefficient-interpretation" class="level4">
<h4 class="anchored" data-anchor-id="t-tests-and-coefficient-interpretation">T Tests and Coefficient Interpretation</h4>
<p>For each coefficient within the model, we can perform a T test to say whether the variable is a significant predictor of <span class="math inline">\(y\)</span>. <span class="math inline">\(H_0\)</span>: The coefficient on <span class="math inline">\(X\)</span> is 0. <span class="math inline">\(H_A\)</span>: The coefficient on <span class="math inline">\(X\)</span> is different from 0.</p>
<p>First we calculate the standard error of each coefficient, <span class="math inline">\(se(\hat{\beta_i})\)</span>, which is the ratio of the average squared error of the model to the total squared error of the predictor. You don’t need to know how to calculate the standard error, but the formula is this: <span class="math display">\[se(\hat{\beta_i})=\sqrt{\dfrac{\sum_i(y_i-\hat{y_i})^2}{(n-2)\sum_i(x_i-\bar{x})^2}}=\sqrt{\dfrac{\sum_i\varepsilon_i}{(n-2)\sum_i(x_i-\bar{x})^2}}\]</span></p>
<p>We use the standard error to calculate the t statistic. <span class="math display">\[t = \dfrac{\hat{\beta_i}}{se(\hat{\beta_i})}\]</span> The t-statistic has <span class="math inline">\(n-k-1\)</span> degrees of freedom, where <span class="math inline">\(n\)</span> is the number of observations and <span class="math inline">\(k\)</span> is the number of predictors. This can be compared to the known distribution (you can use the t-table you got in class!) to get a p-value, which tells us the probability that we see the data we do if the coefficient is actually 0 and <span class="math inline">\(x\)</span> has no effect.</p>
<p>The coefficent we found for speed was <span class="math inline">\(3.93\)</span>, and the standard error is <span class="math inline">\(0.42\)</span>. What is the t-statistic? <input class="webex-solveme nospaces" size="4" data-answer="[&quot;9.36&quot;]"></p>
This is highly significant, since it’s much higher than the values in our t-table. What does that mean?
<div id="radio_OYLNAOOPHT" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_OYLNAOOPHT" value="answer"> <span>Speed is a significant predictor of stopping distance.</span></label><label><input type="radio" autocomplete="off" name="radio_OYLNAOOPHT" value=""> <span>Stopping distance is a significant predictor of speed.</span></label><label><input type="radio" autocomplete="off" name="radio_OYLNAOOPHT" value=""> <span>Speed is NOT a significant predictor of stopping distance.</span></label>
</div>
How do we interpret the coefficient?
<div id="radio_KCFHKWQZHV" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_KCFHKWQZHV" value=""> <span>If speed is 3.93 mph higher, the expected stopping distance is 1 foot larger.</span></label><label><input type="radio" autocomplete="off" name="radio_KCFHKWQZHV" value="answer"> <span>If speed is 1mph higher, the expected stopping distance is 3.93 feet larger.</span></label><label><input type="radio" autocomplete="off" name="radio_KCFHKWQZHV" value=""> <span>If the stopping distance is 3.93 feet larger, the expected mph is 1 larger.</span></label><label><input type="radio" autocomplete="off" name="radio_KCFHKWQZHV" value=""> <span>If the stopping distance is 1 foot larger, the expected mph is 3.93 mph higher.</span></label>
</div>
</section>
</section>
<section id="extra-practice" class="level3">
<h3 class="anchored" data-anchor-id="extra-practice">Extra Practice</h3>
<p>If you need more practice with simple linear regression, here’s another example. This scatterplot shows the relationship between the price of a pack of cigarettes and the number of packs purchased per year divided by the number of people of smoking age for 46 states in 1992.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="regression_workbook_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Use the data in the table to find <span class="math inline">\(\beta_0\)</span>, <span class="math inline">\(\beta_1\)</span>, the <span class="math inline">\(R^2\)</span>, F, and the T statistic associated with the coefficient for a regression using price to predict packs. Be sure to interpret each coefficient that you calculate.</p>
<table class="table">
<caption>Descriptive Statistics for Cigarette Example</caption>
<tbody>
<tr class="odd">
<td>Number of Observations</td>
<td>26</td>
</tr>
<tr class="even">
<td>Mean of Price</td>
<td>1.23</td>
</tr>
<tr class="odd">
<td>Mean of Packs</td>
<td>129.8</td>
</tr>
<tr class="even">
<td>Covariance of Price and Packs</td>
<td>-1.49</td>
</tr>
<tr class="odd">
<td>Variance of Price</td>
<td>0.011</td>
</tr>
<tr class="even">
<td>Variance of Packs</td>
<td>652.4</td>
</tr>
<tr class="odd">
<td>Regression Sum of Squares</td>
<td>9258</td>
</tr>
<tr class="even">
<td>Sum of Squared Errors</td>
<td>20466</td>
</tr>
<tr class="odd">
<td>Standard Error of <span class="math inline">\(\beta_1\)</span></td>
<td>30.4</td>
</tr>
</tbody>
</table>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Tip
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>First, calculate <span class="math inline">\(\beta_1\)</span>: <span class="math display">\[\beta_1 = \dfrac{cov(x,y)}{var(x)}=\dfrac{-1.49}{0.011}=-135.5\]</span> Then, calculate <span class="math inline">\(\beta_0\)</span>: <span class="math display">\[\beta_0 = \bar{y}-\beta_1*\bar{x}=129.8-(-135.5)*1.23=296.5\]</span> The way we interpret these coefficients is: 1) If the price equals 0, the expected number of cigarettes per smoking-aged adult is 296.5. 2) If the price is $1 per pack more, the expected number of packs consumed is 135.5 lower.</p>
<p>Next, calculate the <span class="math inline">\(R^2\)</span>. We need to use the <span class="math inline">\(SSR\)</span> and <span class="math inline">\(SSE\)</span> for this. <span class="math display">\[R^2 = \dfrac{SSR}{SST} = \dfrac{SSR}{SSR+SSE} = \dfrac{9259}{9259+20466} = 0.311\]</span> We interpret this by saying that “31.1% of the variation in cigarette packs consumed can be predicted by the variation in price.”</p>
<p>Next, we calculate the F statistic. <span class="math display">\[
F = \dfrac{MSR}{MSE}=\dfrac{\dfrac{SSR}{DF_{SSR}}}{\dfrac{SSE}{DF_{SSE}}} = \dfrac{\dfrac{9258}{1}}{\dfrac{20466}{46-1-1}}=19.9
\]</span> If we looked it up, we would see that this is very significant, meaning that the model is significantly better than using the mean of packs smoked to predict.</p>
<p>Finally, calculate the t statistic. <span class="math display">\[ T = \dfrac{\beta_1}{se(\beta_1)}=\dfrac{-135.5}{30.4}=-4.45 \]</span> If you look this up in a T table, the p-value is very small, which indicates that price is a good predictor of packs smoked.</p>
</div>
</div>
</div>
</section>
</section>
<section id="multiple-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="multiple-linear-regression">Multiple Linear Regression</h2>
<p>In multiple linear regression, we simply add more explanatory variables. As an example, we will use the cigarette data from above but add another variable: average income. We can use income and the price of cigarettes to predict cigarette consumption.</p>
<p><span class="math display">\[Consumption = \beta_0 + \beta_1*Price+\beta_2*Income\]</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = packs_unlogged ~ price_unlogged + income_unlogged, 
    data = CigarettesB)

Residuals:
   Min     1Q Median     3Q    Max 
-47.23 -14.90  -0.47  14.41  50.94 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      291.2090    38.0066   7.662 1.43e-09 ***
price_unlogged  -144.1001    35.2302  -4.090 0.000186 ***
income_unlogged    0.1353     0.2110   0.642 0.524591    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 21.71 on 43 degrees of freedom
Multiple R-squared:  0.3097,    Adjusted R-squared:  0.2776 
F-statistic: 9.647 on 2 and 43 DF,  p-value: 0.0003458</code></pre>
</div>
</div>
<p>Based on this regression, answer the following questions.</p>
1) Is the model significantly better than using the null model based on the F statistic?
<div id="radio_NNBGNVASXP" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_NNBGNVASXP" value="answer"> <span>Yes</span></label><label><input type="radio" autocomplete="off" name="radio_NNBGNVASXP" value=""> <span>No</span></label><label><input type="radio" autocomplete="off" name="radio_NNBGNVASXP" value=""> <span>Inconclusive</span></label>
</div>
2) Is price a significant predictor of consumption?
<div id="radio_BNWTNCSVRH" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_BNWTNCSVRH" value="answer"> <span>Yes</span></label><label><input type="radio" autocomplete="off" name="radio_BNWTNCSVRH" value=""> <span>No</span></label><label><input type="radio" autocomplete="off" name="radio_BNWTNCSVRH" value=""> <span>Inconclusive</span></label>
</div>
3) Is income a significant predictor of consumption?
<div id="radio_LTOPKPMJFY" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_LTOPKPMJFY" value=""> <span>Yes</span></label><label><input type="radio" autocomplete="off" name="radio_LTOPKPMJFY" value="answer"> <span>No</span></label><label><input type="radio" autocomplete="off" name="radio_LTOPKPMJFY" value=""> <span>Inconclusive</span></label>
</div>
<section id="college-and-beyond-example" class="level3">
<h3 class="anchored" data-anchor-id="college-and-beyond-example">College and Beyond Example</h3>
<p>Let’s try another</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>