<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>ECON 355 - Regression - Lab 9: Transformations and Interactions</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">ECON 355 - Regression</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html">
 <span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-r-walkthroughs" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">R Walkthroughs</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-r-walkthroughs">    
        <li>
    <a class="dropdown-item" href="../03_r_lectures/lecture_1_getting_started.html">
 <span class="dropdown-text">Lesson 1 - Getting Started</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../03_r_lectures/lecture_2_loading_data.html">
 <span class="dropdown-text">Lesson 2 - Loading Data</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-labs" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Labs</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-labs">    
        <li>
    <a class="dropdown-item" href="../02_assignments/lab-02.html">
 <span class="dropdown-text">Lab 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../02_assignments/lab-03.html">
 <span class="dropdown-text">Lab 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../02_assignments/lab-04.html">
 <span class="dropdown-text">Lab 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../02_assignments/lab-05.html">
 <span class="dropdown-text">Lab 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../02_assignments/lab-06.html">
 <span class="dropdown-text">Lab 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../02_assignments/lab-07.html">
 <span class="dropdown-text">Lab 7</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../02_assignments/lab-08.html">
 <span class="dropdown-text">Lab 8</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../02_assignments/lab-09.html">
 <span class="dropdown-text">Lab 9</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../02_assignments/lab-10.html">
 <span class="dropdown-text">Lab 10</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../02_assignments/mini_lab-ttests.html">
 <span class="dropdown-text">T Tests Mini Lab</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-resources" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Resources</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-resources">    
        <li>
    <a class="dropdown-item" href="../00_descriptive/descriptives.html">
 <span class="dropdown-text">Descriptive Statistics</span></a>
  </li>  
    </ul>
  </li>
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#outline" id="toc-outline" class="nav-link active" data-scroll-target="#outline">Outline</a>
  <ul class="collapse">
  <li><a href="#objectives" id="toc-objectives" class="nav-link" data-scroll-target="#objectives">Objectives</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a></li>
  <li><a href="#packages" id="toc-packages" class="nav-link" data-scroll-target="#packages">Packages</a></li>
  <li><a href="#grade" id="toc-grade" class="nav-link" data-scroll-target="#grade">Grade</a></li>
  </ul></li>
  <li><a href="#step-1-load-in-the-data" id="toc-step-1-load-in-the-data" class="nav-link" data-scroll-target="#step-1-load-in-the-data">Step 1: Load in the data</a></li>
  <li><a href="#step-2-income-and-school-quality-analysis---polynomials" id="toc-step-2-income-and-school-quality-analysis---polynomials" class="nav-link" data-scroll-target="#step-2-income-and-school-quality-analysis---polynomials">Step 2: Income and School Quality Analysis - Polynomials</a>
  <ul class="collapse">
  <li><a href="#linear-regression" id="toc-linear-regression" class="nav-link" data-scroll-target="#linear-regression">Linear Regression</a></li>
  <li><a href="#quadratic-regression" id="toc-quadratic-regression" class="nav-link" data-scroll-target="#quadratic-regression">Quadratic Regression</a></li>
  <li><a href="#polynomial-regression" id="toc-polynomial-regression" class="nav-link" data-scroll-target="#polynomial-regression">Polynomial Regression</a></li>
  <li><a href="#interpreting-polynomial-models" id="toc-interpreting-polynomial-models" class="nav-link" data-scroll-target="#interpreting-polynomial-models">Interpreting Polynomial Models</a></li>
  </ul></li>
  <li><a href="#step-3-income-and-school-quality-analysis---logarithms" id="toc-step-3-income-and-school-quality-analysis---logarithms" class="nav-link" data-scroll-target="#step-3-income-and-school-quality-analysis---logarithms">Step 3: Income and School Quality Analysis - Logarithms</a>
  <ul class="collapse">
  <li><a href="#case-1-log-x-level-y" id="toc-case-1-log-x-level-y" class="nav-link" data-scroll-target="#case-1-log-x-level-y">Case 1: Log X, Level Y</a></li>
  <li><a href="#case-2-level-x-log-y" id="toc-case-2-level-x-log-y" class="nav-link" data-scroll-target="#case-2-level-x-log-y">Case 2: Level X, Log Y</a></li>
  <li><a href="#case-3-log-x-log-y" id="toc-case-3-log-x-log-y" class="nav-link" data-scroll-target="#case-3-log-x-log-y">Case 3: Log X, Log Y</a></li>
  </ul></li>
  <li><a href="#step-4-picking-the-best-model" id="toc-step-4-picking-the-best-model" class="nav-link" data-scroll-target="#step-4-picking-the-best-model">Step 4: Picking the Best Model</a></li>
  <li><a href="#step-5-class-size-region-and-scores-dummy-variable-interactions" id="toc-step-5-class-size-region-and-scores-dummy-variable-interactions" class="nav-link" data-scroll-target="#step-5-class-size-region-and-scores-dummy-variable-interactions">Step 5: Class Size, Region, and Scores: Dummy Variable Interactions</a>
  <ul class="collapse">
  <li><a href="#dummy-variables" id="toc-dummy-variables" class="nav-link" data-scroll-target="#dummy-variables">Dummy Variables</a></li>
  <li><a href="#numeric-variable" id="toc-numeric-variable" class="nav-link" data-scroll-target="#numeric-variable">Numeric Variable</a></li>
  <li><a href="#interactions" id="toc-interactions" class="nav-link" data-scroll-target="#interactions">Interactions</a></li>
  </ul></li>
  <li><a href="#step-6-poverty-expenditures-per-student-and-scores-continuous-interactions" id="toc-step-6-poverty-expenditures-per-student-and-scores-continuous-interactions" class="nav-link" data-scroll-target="#step-6-poverty-expenditures-per-student-and-scores-continuous-interactions">Step 6: Poverty, Expenditures per Student, and Scores: Continuous Interactions</a></li>
  <li><a href="#assignment" id="toc-assignment" class="nav-link" data-scroll-target="#assignment">Assignment</a>
  <ul class="collapse">
  <li><a href="#step-1-load-in-the-data-1" id="toc-step-1-load-in-the-data-1" class="nav-link" data-scroll-target="#step-1-load-in-the-data-1">Step 1: Load in the data</a></li>
  <li><a href="#step-2-income-and-life-expectancy-polynomial-regressions" id="toc-step-2-income-and-life-expectancy-polynomial-regressions" class="nav-link" data-scroll-target="#step-2-income-and-life-expectancy-polynomial-regressions">Step 2: Income and Life Expectancy: Polynomial Regressions</a></li>
  <li><a href="#step-3-income-and-life-expectancy-log-transformations" id="toc-step-3-income-and-life-expectancy-log-transformations" class="nav-link" data-scroll-target="#step-3-income-and-life-expectancy-log-transformations">Step 3: Income and Life Expectancy: Log Transformations</a></li>
  <li><a href="#step-4-picking-the-best-model-1" id="toc-step-4-picking-the-best-model-1" class="nav-link" data-scroll-target="#step-4-picking-the-best-model-1">Step 4: Picking the Best Model</a></li>
  <li><a href="#step-5-dummy-numeric-interactions" id="toc-step-5-dummy-numeric-interactions" class="nav-link" data-scroll-target="#step-5-dummy-numeric-interactions">Step 5: Dummy-Numeric Interactions</a></li>
  <li><a href="#step-6-numeric-numeric-interactions" id="toc-step-6-numeric-numeric-interactions" class="nav-link" data-scroll-target="#step-6-numeric-numeric-interactions">Step 6: Numeric-Numeric Interactions</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Lab 9: Transformations and Interactions</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="outline" class="level2">
<h2 class="anchored" data-anchor-id="outline">Outline</h2>
<section id="objectives" class="level3">
<h3 class="anchored" data-anchor-id="objectives">Objectives</h3>
<ul>
<li><p>Perform and interpret a polynomial regression</p></li>
<li><p>Log transform a variable, incorporate it into a regression, and interpret it</p></li>
<li><p>Utilize and interpret interaction terms in regression</p></li>
</ul>
</section>
<section id="data" class="level3">
<h3 class="anchored" data-anchor-id="data">Data</h3>
<p>We will load the <code>CASchools</code> dataset from an R package. This dataset includes data about 420 schools in California in 1996-1998. <a href="https://www.rdocumentation.org/packages/AER/versions/1.2-10/topics/CASchools">This website</a> has information about each of the variables.</p>
</section>
<section id="packages" class="level3">
<h3 class="anchored" data-anchor-id="packages">Packages</h3>
<ul>
<li><p><code>AER</code>: has the data we will use in the lab</p></li>
<li><p><code>ggplot2</code>: used for graphing</p></li>
</ul>
</section>
<section id="grade" class="level3">
<h3 class="anchored" data-anchor-id="grade">Grade</h3>
<p>At the end of the demonstration, there is an assignment for you to do with different data. You will answer associated questions on Canvas.</p>
</section>
</section>
<section id="step-1-load-in-the-data" class="level2">
<h2 class="anchored" data-anchor-id="step-1-load-in-the-data">Step 1: Load in the data</h2>
<p>To do the lab, we will load in the data from the <code>AER</code> package. We also need to calculate the average class size, and create a score that is the average of the reading and math score for the school. This score will be our primary outcome.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list=</span><span class="fu">ls</span>()) <span class="co"># Clears the R environment</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Read in libraries and data</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(AER)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(CASchools)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the number of students per teacher</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>CASchools<span class="sc">$</span>size <span class="ot">&lt;-</span> CASchools<span class="sc">$</span>students<span class="sc">/</span>CASchools<span class="sc">$</span>teachers</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the average of math and reading score</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>CASchools<span class="sc">$</span>score <span class="ot">&lt;-</span> (CASchools<span class="sc">$</span>read <span class="sc">+</span> CASchools<span class="sc">$</span>math) <span class="sc">/</span> <span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="step-2-income-and-school-quality-analysis---polynomials" class="level2">
<h2 class="anchored" data-anchor-id="step-2-income-and-school-quality-analysis---polynomials">Step 2: Income and School Quality Analysis - Polynomials</h2>
<section id="linear-regression" class="level3">
<h3 class="anchored" data-anchor-id="linear-regression">Linear Regression</h3>
<p>The first thing we are going to explore with the data is how the average income in the district is related to the reading and math score. What do you think the relationship between income and test scores would be?</p>
<p>We can first test this with a simple correlation: <code>cor(CASchools$score, CASchools$income)</code>. There is a positive relationship! But let’s run a regression and plot the points to be more thorough.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fit a simple linear model</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>linear_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(score <span class="sc">~</span> income, <span class="at">data =</span> CASchools)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(linear_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = score ~ income, data = CASchools)

Residuals:
    Min      1Q  Median      3Q     Max 
-39.574  -8.803   0.603   9.032  32.530 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 625.3836     1.5324  408.11   &lt;2e-16 ***
income        1.8785     0.0905   20.76   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 13.39 on 418 degrees of freedom
Multiple R-squared:  0.5076,    Adjusted R-squared:  0.5064 
F-statistic: 430.8 on 1 and 418 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Great! If the average income in a district is $1,000 higher, the expected score is 1.88 higher. Income ranges from 5,000 to 55,000, and the scores range from 605 to 707, so that is a pretty big effect! Going from the 1st quartile ($10,639) to the 3rd quartile ($17,629) would increase the score by two thirds of a standard deviation.</p>
<p>Now, let’s plot the data to see what it looks like.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the observations</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(CASchools, <span class="fu">aes</span>(<span class="at">x =</span> income, <span class="at">y =</span> score)) <span class="sc">+</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"District Income (thousands of dollars)"</span>) <span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Test Score"</span>) <span class="sc">+</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">'lm'</span>, <span class="at">formula =</span> y<span class="sc">~</span>x, <span class="at">se =</span> F, <span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lab-09_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" alt="A scatterplot with income on the x axis and score on the y axis. The points have a steep positive relationship from 0 to 10 thousand dollars, but past 10,000 dollars, the relationship is less strong. There is a linear regression line running through that does not fit the points well." width="672"></p>
</div>
</div>
<p>In a linear regression, X and Y are supposed to be linearly related. That means that the effect that X has on Y should be the same at every value of X. However, in this example, it is clearly not the case! The points look curved, but the linear regression line is, well, linear. The regression predicts too high of test scores for low- and high-income districts, but too low of test scores for middle income districts.</p>
<p>Income tends to be strongly right skewed, meaning that most of the observations are grouped around the median, but there are some very high values that make the mean high.</p>
<p>Let’s plot a histogram of income to see if this income variable is right skewed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(CASchools, <span class="fu">aes</span>(<span class="at">x =</span> income)) <span class="sc">+</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Income"</span>) <span class="sc">+</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lab-09_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" alt="A right-skewed histogram of income." width="672"></p>
</div>
</div>
<p>The data is right skewed, so we probably need to correct for that. We can try a few different specifications that will fit the data better.</p>
</section>
<section id="quadratic-regression" class="level3">
<h3 class="anchored" data-anchor-id="quadratic-regression">Quadratic Regression</h3>
<p>We can model test scores as a function of income and income squared. The corresponding regression model is:</p>
<p><span class="math display">\[ TestScore_i = \beta_0 + \beta_1income_i + \beta_2income_i^2 + \varepsilon_i \]</span> This is called a <strong>quadratic regression model</strong>. <span class="math inline">\(income^2\)</span> is treated as an additional explanatory variable. Note that since <span class="math inline">\(income^2\)</span> is not a <em>linear</em> transformation of <span class="math inline">\(income\)</span>, it does not create perfect multicollinearity.</p>
<p>If the relationship between test scores and district income is linear, then the coefficient on <span class="math inline">\(income^2\)</span> will not be significantly different from 0. If the relationship is quadratic, then the relationship will be significantly different from zero. This corresponds to the hypothesis test:</p>
<p><span class="math display">\[ H_0: \beta_2 = 0 \]</span> <span class="math display">\[H_A: \beta_2 \neq 0 \]</span></p>
<p>The p-value we use to test this hypothesis is in the last column of the summary table.</p>
<p>We will use the <code>poly(x, k)</code> function, which will turn whatever <code>x</code> variable we input into a <code>k</code>th order polynomial.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = score ~ poly(income, 2), data = CASchools)

Residuals:
    Min      1Q  Median      3Q     Max 
-44.416  -9.048   0.440   8.347  31.639 

Coefficients:
                 Estimate Std. Error  t value Pr(&gt;|t|)    
(Intercept)      654.1565     0.6209 1053.633  &lt; 2e-16 ***
poly(income, 2)1 277.8568    12.7238   21.838  &lt; 2e-16 ***
poly(income, 2)2 -85.9935    12.7238   -6.758 4.71e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 12.72 on 417 degrees of freedom
Multiple R-squared:  0.5562,    Adjusted R-squared:  0.554 
F-statistic: 261.3 on 2 and 417 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The regression equation is: <span class="math display">\[\hat{TestScore}_i = 654.2 +277.9*income-85.99*income^2\]</span></p>
<p>We now draw the same scatter plot as for the linear model and add the regression line for the quadratic model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(CASchools, <span class="fu">aes</span>(<span class="at">x =</span> income, <span class="at">y =</span> score)) <span class="sc">+</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"District Income (thousands of dollars)"</span>) <span class="sc">+</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Test Score"</span>) <span class="sc">+</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">'lm'</span>, <span class="at">formula =</span> y<span class="sc">~</span>x, <span class="at">se =</span> F, <span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">'lm'</span>, <span class="at">formula =</span> y <span class="sc">~</span> <span class="fu">poly</span>(x, <span class="dv">2</span>), <span class="at">se =</span> F, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lab-09_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" alt="A scatterplot with income on the x axis and score on the y axis. There is a linear prediction line, which does not fit well, and a curved prediction line for the quadratic regression that fits better." width="672"></p>
</div>
</div>
<p>The quadratic function clearly fits the data much better than the linear model.</p>
</section>
<section id="polynomial-regression" class="level3">
<h3 class="anchored" data-anchor-id="polynomial-regression">Polynomial Regression</h3>
<p>We could generalize the quadratic model to include any number of polynomial degrees. <span class="math display">\[ \hat{Y}_i = \beta_0 + \beta_1X_i + \beta_2X_i^2 + \beta_3X_i^3 + ... + \beta_kX_i^k \]</span> A cubic model, for instance, is a polynomial model with the square and cube of the variable, so k = 3.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># estimate a cubic model</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>cubic_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(score <span class="sc">~</span> <span class="fu">poly</span>(income, <span class="dv">3</span>), <span class="at">data =</span> CASchools)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cubic_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = score ~ poly(income, 3), data = CASchools)

Residuals:
   Min     1Q Median     3Q    Max 
-44.28  -9.21   0.20   8.32  31.16 

Coefficients:
                 Estimate Std. Error  t value Pr(&gt;|t|)    
(Intercept)        654.16       0.62 1055.034  &lt; 2e-16 ***
poly(income, 3)1   277.86      12.71   21.867  &lt; 2e-16 ***
poly(income, 3)2   -85.99      12.71   -6.767 4.47e-11 ***
poly(income, 3)3    18.46      12.71    1.452    0.147    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 12.71 on 416 degrees of freedom
Multiple R-squared:  0.5584,    Adjusted R-squared:  0.5552 
F-statistic: 175.4 on 3 and 416 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>One problem with including an extra polynomial is that, as we add additional dimensions, the model becomes harder and harder to interpret. Additionally, we only want to include predictors that make our model better. What happened to the <span class="math inline">\(Adjusted R^2\)</span> between the quadratic regression and the cubic regression? Is the cubic term significant?</p>
<p><strong>See if you can add the line from the cubic equation to your scatterplot.</strong></p>
</section>
<section id="interpreting-polynomial-models" class="level3">
<h3 class="anchored" data-anchor-id="interpreting-polynomial-models">Interpreting Polynomial Models</h3>
<p>Polynomials are difficult to interpret. One method for interpreting polynomials is to take the derivative of the equation. For instance, the cubic model has the following regression equation: <span class="math display">\[ score_i = 654 + 278*income_i -86*income_i^2 +19*income_i^3 +\varepsilon_i \]</span></p>
<p>The derivative of the equation with respect to income would be: <span class="math display">\[ \frac{\partial{score_i}}{\partial{income_i}} = 278-86*2*income_i+19*3*income_i^2\]</span> <span class="math display">\[=278-172*income_i+57*income_i^2 \]</span></p>
<p>We would get the following interpretation: “A one-unit increase in income would lead to a <span class="math inline">\(278-172income_i+57income_i^2\)</span> increase in expected test score.” Confusing!</p>
<p>Alternatively, you can just show a graph of the relationship and predict the effects at a few different values. Let’s predict what happens with the quadratic model when we change income at a few different levels. First, we will test what happens when income goes from 10,000 to 11,000. (Remember that in the data, income is in 1,000s.)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># set up data for prediction</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>new_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">income =</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">11</span>))</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co"># do the prediction</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>Y_hat <span class="ot">&lt;-</span> <span class="fu">predict</span>(quadratic_model, <span class="at">newdata =</span> new_data)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co"># compute the difference</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="fu">diff</span>(Y_hat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       2 
2.962517 </code></pre>
</div>
</div>
<p>How does that compare to the change if income goes from 40 to 41?</p>
</section>
</section>
<section id="step-3-income-and-school-quality-analysis---logarithms" class="level2">
<h2 class="anchored" data-anchor-id="step-3-income-and-school-quality-analysis---logarithms">Step 3: Income and School Quality Analysis - Logarithms</h2>
<p>Another way to specify a nonlinear regression function is to use the natural logarithm of X and/or Y. Logarithms convert changes in variables into percentage changes. This is convenient as many relationships are naturally expressed in terms of percentages. Often, if you are using a right-skewed variable like income, you should automatically take the logarithm.</p>
<p>There are three different kinds of models with log transformations:</p>
<ol type="1">
<li><p>Level-Log: Transform X to be log(X), but do not transform Y (use Y’s <em>level</em>).</p></li>
<li><p>Log-Level: Transform Y to be log(Y), but do not transform X (use X’s <em>level</em>).</p></li>
<li><p>Log-Log: Transform X and Y so that log(Y) ~ log(X).</p></li>
</ol>
<p>The interpretation of the regression coefficients is different in each case. This table shows the interpretation by case:</p>
<table class="table">
<colgroup>
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Case</th>
<th>Equation</th>
<th>Interpretation of <span class="math inline">\(\beta_1\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Level-Log</td>
<td><span class="math display">\[                                                                                               
                                                                 \hat{Y}_i=\beta_0+\beta_1ln(X_i)              
                                                                 \]</span></td>
<td>A 1% change in X is associated with a <span class="math inline">\(0.01*\beta_1\)</span> change in Y.</td>
</tr>
<tr class="even">
<td>Log-Level</td>
<td><span class="math display">\[                                                                                               
                                                                 ln(\hat{Y_i})=\beta_0+\beta_1X_i              
                                                                 \]</span></td>
<td>A 1 unit change in X is associated with a <span class="math inline">\(100*\beta_1\%\)</span> change in Y.</td>
</tr>
<tr class="odd">
<td>Log-Log</td>
<td><span class="math display">\[                                                                                               
                                                                 ln(\hat{Y_i})=\beta_0+\beta_1ln(X_i)          
                                                                 \]</span></td>
<td>A 1% change in X is associated with a <span class="math inline">\(\beta_1\%\)</span> change in Y. This is also the <strong>elasticity</strong> of Y with respect to X.</td>
</tr>
</tbody>
</table>
<section id="case-1-log-x-level-y" class="level3">
<h3 class="anchored" data-anchor-id="case-1-log-x-level-y">Case 1: Log X, Level Y</h3>
<p>The regression form of this model is: <span class="math display">\[ \hat{Y}_i=\beta_0 + \beta_1ln(X_i) \]</span></p>
<p>We do not have to create a new variable to use lm(). We can simply let R know that we want to log-transform X within the function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># estimate a level-log model</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>LinearLog <span class="ot">&lt;-</span> <span class="fu">lm</span>(score <span class="sc">~</span> <span class="fu">log</span>(income), <span class="at">data =</span> CASchools) <span class="co"># log() is the natural log</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(LinearLog)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = score ~ log(income), data = CASchools)

Residuals:
    Min      1Q  Median      3Q     Max 
-43.256  -9.050   0.078   8.230  31.214 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  557.832      4.200  132.81   &lt;2e-16 ***
log(income)   36.420      1.571   23.18   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 12.62 on 418 degrees of freedom
Multiple R-squared:  0.5625,    Adjusted R-squared:  0.5615 
F-statistic: 537.4 on 1 and 418 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the function</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(CASchools, <span class="fu">aes</span>(<span class="at">x =</span> income, <span class="at">y =</span> score)) <span class="sc">+</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"District Income (thousands of dollars)"</span>) <span class="sc">+</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Test Score"</span>) <span class="sc">+</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">'lm'</span>, <span class="at">formula =</span> y<span class="sc">~</span><span class="fu">log</span>(x), <span class="at">se =</span> F, <span class="at">color =</span> <span class="st">"purple"</span>) <span class="sc">+</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lab-09_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Using log transformations allows us to interpret the model using percent changes rather than unit changes. For instance, if the coefficient were 42.6, we would say that “a 1% increase in income is associated with a 0.01*36.4=.364 expected increase in average score”.</p>
<p>If we wanted, we could also calculate the estimated effect at different values of X like we did for polynomials.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># set up new data</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>new_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">income =</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">11</span>, <span class="dv">40</span>, <span class="dv">41</span>))</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="co"># predict the outcomes</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>Y_hat <span class="ot">&lt;-</span> <span class="fu">predict</span>(LinearLog, <span class="at">newdata =</span> new_data)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="co"># compute the expected difference</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>Y_hat_matrix <span class="ot">&lt;-</span> <span class="fu">matrix</span>(Y_hat, <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>Y_hat_matrix[, <span class="dv">2</span>] <span class="sc">-</span> Y_hat_matrix[, <span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.471166 0.899297</code></pre>
</div>
</div>
<p>Going from 10 to 11 thousand dollars has a bigger effect than going from 40 to 41 thousand dollars.</p>
</section>
<section id="case-2-level-x-log-y" class="level3">
<h3 class="anchored" data-anchor-id="case-2-level-x-log-y">Case 2: Level X, Log Y</h3>
<p>We can just log the dependent variable and keep x level. The model is: <span class="math display">\[ ln(Y_i) = \beta_0 + \beta_1X_i +\varepsilon_i \]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># estimate a log-linear model</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>LogLinear <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(score) <span class="sc">~</span> income, <span class="at">data =</span> CASchools)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(LogLinear)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(score) ~ income, data = CASchools)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.06285 -0.01340  0.00114  0.01413  0.04913 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 6.4393623  0.0023638 2724.16   &lt;2e-16 ***
income      0.0028441  0.0001396   20.37   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.02065 on 418 degrees of freedom
Multiple R-squared:  0.4982,    Adjusted R-squared:  0.497 
F-statistic:   415 on 1 and 418 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The estimated regression function is: <span class="math display">\[ ln(TestScore_i) = 6.439 + 0.00284*income_i+\varepsilon_i \]</span> This means that if income increases by 1 unit ($1,000), then expected test score increases by <span class="math inline">\(100*0.00284=0.284\%\)</span>.</p>
</section>
<section id="case-3-log-x-log-y" class="level3">
<h3 class="anchored" data-anchor-id="case-3-log-x-log-y">Case 3: Log X, Log Y</h3>
<p>The log-log regression model is:</p>
<p><span class="math display">\[
ln(Y_i) = \beta_0+\beta_1ln(X_i)=\varepsilon_i
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># estimate the log-log model</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>LogLog <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(score) <span class="sc">~</span> <span class="fu">log</span>(income), <span class="at">data =</span> CASchools)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(LogLog)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(score) ~ log(income), data = CASchools)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.066458 -0.013658  0.000508  0.012903  0.047856 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 6.336349   0.006453  981.90   &lt;2e-16 ***
log(income) 0.055419   0.002414   22.96   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.01938 on 418 degrees of freedom
Multiple R-squared:  0.5578,    Adjusted R-squared:  0.5567 
F-statistic: 527.2 on 1 and 418 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The equation from this model is: <span class="math display">\[ ln(TestScore_i) = 6.34 + 0.06*ln(income_i) +\varepsilon_i \]</span></p>
<p>A 1% increase in thousands of dollars of income is associated with a 0.06 % increase in test score.</p>
<p>The following code plots all of the log models on top of the scatterplot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>CASchools<span class="sc">$</span>pred_log_level <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">predict</span>(LogLinear))</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>CASchools<span class="sc">$</span>pred_log_log <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">predict</span>(LogLog))</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(CASchools, <span class="fu">aes</span>(<span class="at">x =</span> income, <span class="at">y =</span> score)) <span class="sc">+</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"District Income (thousands of dollars)"</span>) <span class="sc">+</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Test Score"</span>) <span class="sc">+</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">'lm'</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">se =</span> F, <span class="at">color =</span> <span class="st">"green4"</span>) <span class="sc">+</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">'lm'</span>, <span class="at">formula =</span> y <span class="sc">~</span> <span class="fu">log</span>(x), <span class="at">se =</span> F, <span class="at">color =</span> <span class="st">"purple"</span>) <span class="sc">+</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> pred_log_level), <span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> pred_log_log), <span class="at">color =</span> <span class="st">"red3"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lab-09_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The log-level and level-level models look essential the same, while the level-log and log-log models look the same.</p>
</section>
</section>
<section id="step-4-picking-the-best-model" class="level2">
<h2 class="anchored" data-anchor-id="step-4-picking-the-best-model">Step 4: Picking the Best Model</h2>
<p>We can compare the adjusted R2 to see if any model has a significantly better fit than the rest.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compute the adj. R^2 for the nonlinear models</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>adj_R2 <span class="ot">&lt;-</span><span class="fu">rbind</span>(<span class="st">"linear"</span> <span class="ot">=</span> <span class="fu">summary</span>(linear_model)<span class="sc">$</span>adj.r.squared,</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="st">"quadratic"</span> <span class="ot">=</span> <span class="fu">summary</span>(quadratic_model)<span class="sc">$</span>adj.r.squared,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="st">"cubic"</span> <span class="ot">=</span> <span class="fu">summary</span>(cubic_model)<span class="sc">$</span>adj.r.squared,</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="st">"LinearLog"</span> <span class="ot">=</span> <span class="fu">summary</span>(LinearLog)<span class="sc">$</span>adj.r.squared,</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="st">"LogLinear"</span> <span class="ot">=</span> <span class="fu">summary</span>(LogLinear)<span class="sc">$</span>adj.r.squared,</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="st">"LogLog"</span> <span class="ot">=</span> <span class="fu">summary</span>(LogLog)<span class="sc">$</span>adj.r.squared</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a><span class="co"># assign column names</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(adj_R2) <span class="ot">&lt;-</span> <span class="st">"adj_R2"</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>adj_R2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             adj_R2
linear    0.5063795
quadratic 0.5540444
cubic     0.5552279
LinearLog 0.5614605
LogLinear 0.4970106
LogLog    0.5567251</code></pre>
</div>
</div>
<p>The Linear and Log-Linear models both have lower <span class="math inline">\(R^2\)</span> values, but the others are pretty similar. So how do we choose a model?</p>
<p>Let’s look at a plot that shows both the linear-log and quadratic models, potentially our two best models.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the observations</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(CASchools, <span class="fu">aes</span>(<span class="at">x =</span> income, <span class="at">y =</span> score)) <span class="sc">+</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"District Income (thousands of dollars)"</span>) <span class="sc">+</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Test Score"</span>) <span class="sc">+</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">'lm'</span>, <span class="at">formula =</span> y<span class="sc">~</span><span class="fu">poly</span>(x,<span class="dv">2</span>), <span class="at">se =</span> F, <span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">'lm'</span>, <span class="at">formula =</span> y<span class="sc">~</span><span class="fu">log</span>(x), <span class="at">se =</span> F, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="lab-09_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Neither appears to be more appropriate for the data. I would then choose based on theory.</p>
<ol type="1">
<li><p>It’s easier to interpret the linear-log model, and it makes sense that income would be interpreted as percent changes since it is right skewed.</p></li>
<li><p>In the quadratic model, if we continued to higher values of income, scores would eventually go down, which doesn’t make much sense.</p></li>
</ol>
<p>I would go with the linear-log model.</p>
</section>
<section id="step-5-class-size-region-and-scores-dummy-variable-interactions" class="level2">
<h2 class="anchored" data-anchor-id="step-5-class-size-region-and-scores-dummy-variable-interactions">Step 5: Class Size, Region, and Scores: Dummy Variable Interactions</h2>
<p>The last section dealt with transformations to make non-linear data into linear data. Now, we’ll look at interactions.</p>
<p>I’m interested in whether class size affects test scores. I also think that the effect will vary based on region - in some regions like the bay area, students will be privileged enough that class size won’t matter as much, but in poorer regions like the central valley, I think class size will have a larger effect.</p>
<p>I will create a region variable, then do a regression with the interaction.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create region variable</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>CASchools<span class="sc">$</span>region <span class="ot">&lt;-</span> <span class="st">"Northern CA"</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>CASchools<span class="sc">$</span>region[CASchools<span class="sc">$</span>county <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Los Angeles"</span>,</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>                                         <span class="st">"San Bernardino"</span>,</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>                                         <span class="st">"Riverside"</span>,</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>                                         <span class="st">"San Diego"</span>,</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>                                         <span class="st">"Imperial"</span>)] <span class="ot">&lt;-</span> <span class="st">"Southern CA"</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>CASchools<span class="sc">$</span>region[CASchools<span class="sc">$</span>county <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Alameda"</span>, </span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>                                         <span class="st">"Contra Costa"</span>, </span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>                                         <span class="st">"Marin"</span>, </span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>                                         <span class="st">"San Francisco"</span>, </span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>                                         <span class="st">"San Mateo"</span>, </span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>                                         <span class="st">"Santa Clara"</span>, </span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>                                         <span class="st">"Solano"</span>)] <span class="ot">&lt;-</span> <span class="st">"Bay Area"</span></span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>CASchools<span class="sc">$</span>region[CASchools<span class="sc">$</span>county <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Fresno"</span>, </span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>                                         <span class="st">"Inyo"</span>, </span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a>                                         <span class="st">"Kern"</span>, </span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>                                         <span class="st">"Kings"</span>, </span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a>                                         <span class="st">"Tulare"</span>, </span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>                                         <span class="st">"Alpine"</span>, </span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a>                                         <span class="st">"Amador"</span>, </span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a>                                         <span class="st">"Calaveras"</span>, </span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a>                                         <span class="st">"Madera"</span>, </span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a>                                         <span class="st">"Mariposa"</span>, </span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a>                                         <span class="st">"Merced"</span>, </span>
<span id="cb25-26"><a href="#cb25-26" aria-hidden="true" tabindex="-1"></a>                                         <span class="st">"Mono"</span>,</span>
<span id="cb25-27"><a href="#cb25-27" aria-hidden="true" tabindex="-1"></a>                                         <span class="st">"San Joaquin"</span>,</span>
<span id="cb25-28"><a href="#cb25-28" aria-hidden="true" tabindex="-1"></a>                                         <span class="st">"Stanislaus"</span>, </span>
<span id="cb25-29"><a href="#cb25-29" aria-hidden="true" tabindex="-1"></a>                                         <span class="st">"Tuolumne"</span>)] <span class="ot">&lt;-</span> <span class="st">"Central CA"</span></span>
<span id="cb25-30"><a href="#cb25-30" aria-hidden="true" tabindex="-1"></a>CASchools<span class="sc">$</span>region[CASchools<span class="sc">$</span>county <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Monterey"</span>,</span>
<span id="cb25-31"><a href="#cb25-31" aria-hidden="true" tabindex="-1"></a>                                         <span class="st">"San Benito"</span>,</span>
<span id="cb25-32"><a href="#cb25-32" aria-hidden="true" tabindex="-1"></a>                                         <span class="st">"San Luis Obispo"</span>,</span>
<span id="cb25-33"><a href="#cb25-33" aria-hidden="true" tabindex="-1"></a>                                         <span class="st">"Santa Barbara"</span>,</span>
<span id="cb25-34"><a href="#cb25-34" aria-hidden="true" tabindex="-1"></a>                                         <span class="st">"Santa Cruz"</span>,</span>
<span id="cb25-35"><a href="#cb25-35" aria-hidden="true" tabindex="-1"></a>                                         <span class="st">"Ventura"</span>)] <span class="ot">&lt;-</span> <span class="st">"Central Coast"</span></span>
<span id="cb25-36"><a href="#cb25-36" aria-hidden="true" tabindex="-1"></a>dummy_interaction <span class="ot">&lt;-</span> <span class="fu">lm</span>(score <span class="sc">~</span> size <span class="sc">+</span> region <span class="sc">+</span> region<span class="sc">*</span>size, <span class="at">data =</span> CASchools)</span>
<span id="cb25-37"><a href="#cb25-37" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dummy_interaction)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = score ~ size + region + region * size, data = CASchools)

Residuals:
    Min      1Q  Median      3Q     Max 
-46.385 -11.779   0.117  11.505  39.283 

Coefficients:
                         Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)               798.139     24.954  31.985  &lt; 2e-16 ***
size                       -6.745      1.312  -5.142 4.22e-07 ***
regionCentral CA         -146.829     30.003  -4.894 1.42e-06 ***
regionCentral Coast       -40.919     41.065  -0.996   0.3196    
regionNorthern CA        -148.694     28.380  -5.239 2.58e-07 ***
regionSouthern CA         -86.391     36.227  -2.385   0.0175 *  
size:regionCentral CA       6.294      1.556   4.046 6.22e-05 ***
size:regionCentral Coast    1.760      2.079   0.847   0.3978    
size:regionNorthern CA      7.206      1.489   4.840 1.85e-06 ***
size:regionSouthern CA      3.768      1.819   2.071   0.0390 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 16.22 on 410 degrees of freedom
Multiple R-squared:  0.2906,    Adjusted R-squared:  0.275 
F-statistic: 18.66 on 9 and 410 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The reference category is the “Bay Area” because it is first alphabetically. If we wanted to use a different reference level, we can change that using the <code>relevel()</code> function. For isntance, if we want to change the reference level to be Central California, we would run:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>CASchools<span class="sc">$</span>region <span class="ot">&lt;-</span> <span class="fu">relevel</span>(<span class="fu">as.factor</span>(CASchools<span class="sc">$</span>region), <span class="at">ref =</span> <span class="st">"Central CA"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>However, we will stick with the Bay Area as our reference for this example.</p>
<section id="dummy-variables" class="level3">
<h3 class="anchored" data-anchor-id="dummy-variables">Dummy Variables</h3>
<p>We’ll first look at the dummy variables. The coefficient on “Central California” is -146.8, and it is very significant. What this says is that, for every class size, the expected test score is 146.8 points lower in Central California than in the Bay Area. The range of the score variable is 605 to 707, so this is a huge difference! Northern California and Southern California also have significantly lower scores than the Bay Area.</p>
</section>
<section id="numeric-variable" class="level3">
<h3 class="anchored" data-anchor-id="numeric-variable">Numeric Variable</h3>
<p>The coefficient on class size is -6.7. For every additional child per teacher on average, the expected score lowers by almost 7 points. This makes sense because we know class size is an important determinant of student outcomes. Class size ranges from 14 to 26, so if a class jumps from the lowest class size to the highest, expected scores would decline by about 7*8 = 56 points.</p>
<p>However, since we have interactions, the only place that has the coefficient -6.7 on class size is the Bay Area.</p>
</section>
<section id="interactions" class="level3">
<h3 class="anchored" data-anchor-id="interactions">Interactions</h3>
<p>The interaction between the Northern California region and class size is 7.2. That means that, in a district in Northern California, the coefficient on class size is <span class="math inline">\(\beta_1+\beta_3=-6.7+7.2=0.5\)</span>. If average class size increases by one student, the expected test score increases by half a point. (In reality, if we ran a regression on Northern California alone, this probably wouldn’t be a significant variable.)</p>
<p>What we can take away from this is that larger classes have the most negative effect in the Bay Area, while in Northern California and Central California, they don’t seem to make a difference. The opposite of my hypothesis!</p>
</section>
</section>
<section id="step-6-poverty-expenditures-per-student-and-scores-continuous-interactions" class="level2">
<h2 class="anchored" data-anchor-id="step-6-poverty-expenditures-per-student-and-scores-continuous-interactions">Step 6: Poverty, Expenditures per Student, and Scores: Continuous Interactions</h2>
<p>If we have an interaction between two continuous variables, the interpretation is a little more confusing. Let’s try. I hypothesize that in schools where more of the students are on free or reduced lunch, expenditures will have a more positive effect.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>interaction <span class="ot">&lt;-</span> <span class="fu">lm</span>(score <span class="sc">~</span> lunch <span class="sc">+</span> expenditure <span class="sc">+</span> lunch<span class="sc">*</span>expenditure, <span class="at">data =</span> CASchools)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(interaction)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = score ~ lunch + expenditure + lunch * expenditure, 
    data = CASchools)

Residuals:
    Min      1Q  Median      3Q     Max 
-34.975  -5.489   0.024   6.075  34.192 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        6.474e+02  6.127e+00 105.656  &lt; 2e-16 ***
lunch             -2.949e-01  1.280e-01  -2.304   0.0217 *  
expenditure        6.295e-03  1.116e-03   5.639 3.16e-08 ***
lunch:expenditure -5.705e-05  2.341e-05  -2.436   0.0153 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.027 on 416 degrees of freedom
Multiple R-squared:  0.7771,    Adjusted R-squared:  0.7755 
F-statistic: 483.5 on 3 and 416 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li><p>The coefficient on lunch is -0.29, which means that if the percent of students on free lunch goes up by one percentage point, the expected score goes down by 0.29 points.</p></li>
<li><p>The coefficient on expenditure per student is 0.006, which means that if expenditure per student goes up by $1,000, the expected score goes up by 6.</p></li>
</ul>
<p>How do we interpret the interaction term? The term is very small and negative. This means that if there<br>
are more students on free lunch, the effect of more expenditures is less positive. Or, alternatively, if<br>
expenditure is higher, then the effect of having more students on free lunch is more negative. (I would<br>
guess the first interpretation is more accurate.)</p>
<p>Just like with polynomials, we could also use derivatives to calculate the effect.</p>
<p><span class="math display">\[
\hat{Y}=\beta_0+\beta_1X+\beta_2Z+\beta_3X*Z
\]</span></p>
<p>Taking the derivative with respect to X:</p>
<p><span class="math display">\[
\frac{\partial{Y}}{\partial{X}}=\beta_1+\beta_3*Z
\]</span></p>
<p>So, the effect of X is dependent on Z. Let’s calculate the effect of expenditure at the median value of free school lunch percent, 41.8.</p>
<p><span class="math display">\[
Y=647.4+(-0.29-0.000057*41.8)*X=647.4-0.29X
\]</span></p>
<p>Practically, this effect isn’t significant, even if it’s statistically significant. (See those little stars?) However, this still gives you the idea of what the point of interaction terms is. You should only include interaction terms if you think there is a good reason for them to be included.</p>
<p>If I were to report these results to a policy expert, I would tell them that in areas with more students on free or reduced lunch, it will take more resources to get similar outcomes.</p>
</section>
<section id="assignment" class="level2">
<h2 class="anchored" data-anchor-id="assignment">Assignment</h2>
<p>Do a similar analysis to the above using the life expectancy/insurance data. Follow these steps, and answer the questions on Canvas.</p>
<section id="step-1-load-in-the-data-1" class="level3">
<h3 class="anchored" data-anchor-id="step-1-load-in-the-data-1">Step 1: Load in the data</h3>
<p>You should have the code to load and merge the data from lab 7. (If you do not, you can email me telling me the importance of saving your R scripts, and I will give you the code or data.) You will need all of the sheets loaded and merged: life expectancy, income, insurance, and region. You will also need to calculate the uninsured rate like you did before.</p>
</section>
<section id="step-2-income-and-life-expectancy-polynomial-regressions" class="level3">
<h3 class="anchored" data-anchor-id="step-2-income-and-life-expectancy-polynomial-regressions">Step 2: Income and Life Expectancy: Polynomial Regressions</h3>
<p>Graph the relationship between income per capita (x axis) and female life expectancy (y axis), like we did in step 2. Run a linear regression predicting female life expectancy from <strong>income per capita</strong>. Then, run a quadratic regression.</p>
</section>
<section id="step-3-income-and-life-expectancy-log-transformations" class="level3">
<h3 class="anchored" data-anchor-id="step-3-income-and-life-expectancy-log-transformations">Step 3: Income and Life Expectancy: Log Transformations</h3>
<p>Run a regression where you log transform median household income, and one where you transform both median household income and life expectancy.</p>
</section>
<section id="step-4-picking-the-best-model-1" class="level3">
<h3 class="anchored" data-anchor-id="step-4-picking-the-best-model-1">Step 4: Picking the Best Model</h3>
<p>Compare all the models you ran.</p>
</section>
<section id="step-5-dummy-numeric-interactions" class="level3">
<h3 class="anchored" data-anchor-id="step-5-dummy-numeric-interactions">Step 5: Dummy-Numeric Interactions</h3>
<p>Perform a regression with female life expectancy as the outcome variable and <strong>region</strong>, <strong>uninsured rate</strong>, and the <strong>interaction between region and uninsured rate</strong> as your explanatory variables.</p>
</section>
<section id="step-6-numeric-numeric-interactions" class="level3">
<h3 class="anchored" data-anchor-id="step-6-numeric-numeric-interactions">Step 6: Numeric-Numeric Interactions</h3>
<p>Perform a regression with life expectancy as the outcome variable and <strong>uninsured rate</strong>, <strong>median household income</strong>, and the <strong>interaction between uninsured rate and median household income</strong> as the predictor variables. (Do not take the log of income, even though you probably would in a real analysis.)</p>
<div class="cell">

</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>